### ISSUE TITLE
store alt

### ISSUE THREAD

**Issue by gedw99** [OpenSourceOptimist/skyflow#4]
mongo is great

but would be nice to have postresql / cockroach ....

there is a open source mongodb that uses postresql under the hood.
https://blog.ferretdb.io/ferretdb-1-0-ga-opensource-mongodb-alternative/

https://github.com/FerretDB/FerretDB

**Comment by OpenSourceOptimist** [comment]
> there is a open source mongodb

ME: *Thinking MongoDB is surly opensource, checks wikipedia, sees SSPL, mild panic ensures...*

How did I not know MongoDB is uses the sketchy Server Side Public License...

Maybe I will just have to grow up and learn SQL :fearful:

**Comment by OpenSourceOptimist** [comment]
After some messing around with postgres  I have come to the realization that life is to short and my free time is to precious to spend it learning SQL. It is really good to here ferretdb exists, but for the time beeing I will continiue with my filthy proprietary mongo container.
